-- V2__new_migration.sql

-- Create table for PetType
CREATE TABLE types (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL
);

-- Create table for Owner
CREATE TABLE owners (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        first_name VARCHAR(255),
                        last_name VARCHAR(255),
                        address VARCHAR(255),
                        city VARCHAR(255),
                        telephone VARCHAR(20)
);

-- Create table for Pet
CREATE TABLE pets (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255),
                      type_id BIGINT,
                      owner_id BIGINT,
                      birth_date DATE,
                      FOREIGN KEY (type_id) REFERENCES types(id),
                      FOREIGN KEY (owner_id) REFERENCES owners(id)
);

-- Create table for Visit
CREATE TABLE visits (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        date DATE,
                        description TEXT,
                        pet_id BIGINT,
                        FOREIGN KEY (pet_id) REFERENCES pets(id)
);

-- Create table for Speciality
CREATE TABLE specialties (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             description TEXT
);

-- Create table for Vet
CREATE TABLE vets (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      first_name VARCHAR(255),
                      last_name VARCHAR(255)
);

-- Create table for vet_specialties (many-to-many relationship between Vet and Speciality)
CREATE TABLE vet_specialties (
                                 vet_id BIGINT,
                                 speciality_id BIGINT,
                                 PRIMARY KEY (vet_id, speciality_id),
                                 FOREIGN KEY (vet_id) REFERENCES vets(id),
                                 FOREIGN KEY (speciality_id) REFERENCES specialties(id)
);

